version: 2

jobs:
  vtk:
    docker:
      - image: openturns/archlinux-mingw
        environment:
          MAKEFLAGS: "-j2"
    steps:
      - run:
          name: Build
          command: aurman -Syu --noconfirm --noedit --pgp_fetch mingw-w64-vtk-git

  paraview:
    docker:
      - image: openturns/archlinux-mingw
        environment:
          MAKEFLAGS: "-j2"
    steps:
      - run:
          name: Build
          command: aurman -Syu --noconfirm --noedit --pgp_fetch mingw-w64-paraview-git
      - run:
          name: Plugin
          command: aurman -S qt5-xmlpatterns --noconfirm --noedit && cd /tmp && git clone https://github.com/jschueller/paraview-plugin-example.git && cd paraview-plugin-example && x86_64-w64-mingw32-cmake . && make

workflows:
  version: 2
  commit:
    jobs:
      - vtk
      - paraview
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 4"
          filters:
            branches:
              only:
                - master
    jobs:
      - vtk
      - paraview
