version: 2

jobs:
  vtk-git:
    docker:
      - image: openturns/archlinux-mingw
        environment:
          MAKEFLAGS: "-j2"
    steps:
      - run:
          name: Build
          no_output_timeout: 15m
          command: |
            git clone https://aur.archlinux.org/mingw-w64-fmt.git /tmp/fmt && cd /tmp/fmt && makepkg -sfi --nocheck --noconfirm
            aurman -Syu --noconfirm --noedit --pgp_fetch mingw-w64-vtk-git

  paraview-git:
    docker:
      - image: openturns/archlinux-mingw
        environment:
          MAKEFLAGS: "-j2"
    steps:
      - run:
          name: Build
          command: |
            git clone https://aur.archlinux.org/mingw-w64-fmt.git /tmp/fmt && cd /tmp/fmt && makepkg -sfi --nocheck --noconfirm
            aurman -Syu --noconfirm --noedit --pgp_fetch mingw-w64-paraview-git
      - run:
          name: Plugin
          command: cd /tmp && git clone https://github.com/jschueller/paraview-plugin-example.git && cd paraview-plugin-example && x86_64-w64-mingw32-cmake -Dqt_xmlpatterns_executable=/usr/bin/x86_64-w64-mingw32-xmlpatterns . && make VERBOSE=1

  paraview:
    docker:
      - image: openturns/archlinux-mingw
        environment:
          MAKEFLAGS: "-j2"
    steps:
      - run:
          name: Build
          command: aurman -Syu --noconfirm --noedit --pgp_fetch mingw-w64-paraview
      - run:
          name: Plugin
          command: cd /tmp && git clone https://github.com/jschueller/paraview-plugin-example.git && cd paraview-plugin-example && x86_64-w64-mingw32-cmake -Dqt_xmlpatterns_executable=/usr/bin/x86_64-w64-mingw32-xmlpatterns . && make VERBOSE=1

workflows:
  version: 2
  commit:
    jobs:
      - vtk-git
      - paraview-git
      - paraview

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 4"
          filters:
            branches:
              only:
                - master
    jobs:
      - vtk-git
      - paraview-git
